### ISSUE TITLE
question about controlnet

### ISSUE THREAD

**Issue by stime111** [Stable-X/StableNormal#1]
First of all,thanks for your great work!
Then I find the controlnet and dino controlnet are both used in the StableNormal pipeline,does that mean we can use both of the two controller during normal estimation?

**Comment by lingtengqiu** [comment]
Yes, In the arxiv version, we do not use two controlnet. Specifically, for dino condition ,we use a lightweight CNN to projection. But, recently, we find using another controlent to inject dino features  is more effectively and better than a simple lightweight network.

**Comment by JunyuanDeng** [comment]
> Yes, In the arxiv version, we do not use two controlnet. Specifically, for dino condition ,we use a lightweight CNN to projection. But, recently, we find using another controlent to inject dino features is more effectively and better than a simple lightweight network.

Hello，

Any plan to release this version?
