### ISSUE TITLE
Detial of regularizing 2dgs 

### ISSUE THREAD

**Issue by Binyr** [Stable-X/StableNormal#15]
Hi, 

I use your model to inference normal maps of DTU dataset. And regularize 2dgs normal map after iter 7k with lambda 0.05. The loss is similar to the 2dgs depth_normal regularizing loss. Finnally, I get a slightly different results shown below. Could you provide some details to help me reproduce these results? 

![image](https://github.com/user-attachments/assets/c84ceeea-9423-4104-a74a-8af1446be9f3)

Thank you!
Yanrui

**Comment by seulqxq** [comment]
Hi, can I ask you how to combine stablenormalX with 2dgs?

**Comment by hugoycj** [comment]
@seulqxq We have uploaded the train with normal scripts to https://github.com/hugoycj/2d-gaussian-splatting-great-again/blob/main/scripts/train_wmask_wnormal.sh. Feel free to have a try

**Comment by seulqxq** [comment]
@hugoycj  Thank you very much. I will undertake an attempt.

**Comment by seulqxq** [comment]
@hugoycj Hello, I'm sorry to bother you again, I used 2d-gaussian-splatting-great-again to train my own data set, but there was an error. Could you please tell me if you have ever encountered such a situation?
![image](https://github.com/user-attachments/assets/bd87df28-968f-4d30-92d2-d4886d569f65)
Here is the structure of my dataset and some versions of the library：
torch                                 2.3.1+cu118
torchaudio                        2.3.1+cu118
mini-dust3r                       0.1.2
gaustudio                          0.1.0
![image](https://github.com/user-attachments/assets/0d49ac3b-5d4b-4b68-99e5-54ffe9311194)

**Comment by hugoycj** [comment]
@seulqxq We have a modified mini-dust3r under dev branch https://github.com/GAP-LAB-CUHK-SZ/gaustudio/tree/develop/submodules/mini-dust3r. You can try to install this one

**Comment by seulqxq** [comment]
Thank you so much for your quick reply! It work
