### ISSUE TITLE
Normal orientation convention. 

### ISSUE THREAD

**Issue by gaetan-landreau** [Stable-X/StableNormal#18]
Hi ! Thanks for your amazing job ! 🤗
I couldn't find in the paper nor in any open/closed issues some word regarding the normal orientation convention that you used. 🥲
Are normals oriented the same way DSINE did (right-handed coordinate system) ? 
Thanks a lot ! 🙏🏻

**Comment by lingtengqiu** [comment]
Hi, the Normal orientation coordinate is defined as following graph
```bash
             y
            ^
             |
             |
 x<-----
             /
            /
          z
```
Normal oriented is as the same way as DSINE.
