### ISSUE TITLE
DINO v.s. CLIP?

### ISSUE THREAD

**Issue by snowflakewang** [Stable-X/StableNormal#22]
Hello, thank you for your great work in SOTA normal estimation and down-stream tasks!

I am curious about the vision encoder you used. Have you ever tried to use CLIP Vision Encoder or straightly choose DINO? If you have tried CLIP before, which aspect do you think CLIP is not as optimal as DINO?

Thanks a lot! :)

**Comment by lingtengqiu** [comment]
CLIP feature provide global features while DINO features provide more local textural information. At the beginning, We attempt to use CLIP features as condition hints but emperical experiments obviously show  the model with CLIP features struggle to recover fine-grained surface normal.  Therefore, we suggest you use DINO feature as guidance information.
