### ISSUE TITLE
How to compute xt+ in equation 7?

### ISSUE THREAD

**Issue by liylo** [Stable-X/StableNormal#29]
Thanks for your great work! I get confused about xt+ in equation 7.
![image](https://github.com/user-attachments/assets/fa4d11bb-fbc1-445e-a647-2d4fab4a2b65)

It should be computed in GenPercept way as follows,
![image](https://github.com/user-attachments/assets/0567acfc-7296-4bb6-84a9-e952610cc05b)

or it should be computed in DDPM way?
![image](https://github.com/user-attachments/assets/d9a35b7a-75eb-44e2-a825-45434f75b854)

By the way, how do you choose xt+ in YOSO training, rand in (0,T) or fix to 401?

**Comment by hugoycj** [comment]
We adopt the xt parameterization, which means that conditioned on both gaussian noise ε  and timestamp t, we finetune the latent diffusion model to directly regress xt. During YOSO training, we randomly sample t from the interval (0,T), where T=1000. This formulation allows YOSO to handle a more general case than GenPercept, with GenPercept being a special case when t=0.

**Comment by liylo** [comment]
Thanks a lot!
