### ISSUE TITLE
Dino Condition

### ISSUE THREAD

**Issue by rwn17** [Stable-X/StableNormal#32]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/be8c2258-05ca-4afa-9b51-54e01163cd75" />

Thank you for your excellent work! From the figures, it appears that the UNet is conditioned on the encoded VAE latent. However, the writing emphasizes conditioning on DINO for semantic guidance. Could you please clarify this, or am I misunderstanding something?

Bests,
Weining

**Comment by lingtengqiu** [comment]
Dino features provide high-level  semantic features. If you apply KNN-based method to visualize these features, you could find  the points from the same plane have more similarity features, implying these points being same normal directions.
