### ISSUE TITLE
mono depth estimation

### ISSUE THREAD

**Issue by luochunfen** [Stable-X/StableNormal#5]
Thanks for your great work! Is there any plan to use StableNormal to train a mono depth estimation model?

**Comment by lingtengqiu** [comment]
Thanks for you suggestion.
We will release Stable-Normal before 9.01.2024!

**Comment by luochunfen** [comment]
> Thanks for you suggestion. We will release Stable-Depth before 09.01.2024!

Terrific！Thank you for your job.
