### ISSUE TITLE
How to use the model?

### ISSUE THREAD

**Issue by DaLi-Jack** [Stable-X/StableNormal#6]
Hi! Congratulations on your great work!
Could you kindly provide detailed steps on how to properly use the model? 
Additionally, it would be greatly appreciated if the README could be updated to include these instructions for the benefit of other users as well.
Thank you very much for your time and assistance. I look forward to your response.

**Comment by hugoycj** [comment]
Will be updated today!

**Comment by Stable-X** [comment]
Code cleanup may require a few more days. We anticipate releasing by Friday. For basic usage examples, please refer to the Gradio app code

**Comment by hugoycj** [comment]
@DaLi-Jack We've implemented a Torch Hub Version to facilitate easy integration into any of your projects with just a few lines of code. Feel free to give it a try! You can find more information and usage instructions [here](https://github.com/Stable-X/StableNormal?tab=readme-ov-file#usage).

**Comment by DaLi-Jack** [comment]
Thanks for your help!
