### ISSUE TITLE
How to get npy result?

### ISSUE THREAD

**Issue by Binyr** [Stable-X/StableNormal#8]
Hi, 

Thanks for your great work!

I use your model to predict normal in camera space, and then transfer it to world space. The results has much artifacts! I guess this  is caused by lossy compression of jpg file format.  Examples show below.

So, would you mind provide me a interface to obtain a lossless results.

Thank you,
Yanrui

![image](https://github.com/user-attachments/assets/f8630bdc-342d-4cfa-92a6-d9fc81651f47)
![image](https://github.com/user-attachments/assets/1594246f-3920-4694-82c0-27dec5360dd5)

**Comment by hugoycj** [comment]
You can save as .png to avoid artifacts caused by compression. We highly recommand .png compared to .npy, which is accurate enough for most downstream task and save space
