### ISSUE TITLE
Training codes and dataset

### ISSUE THREAD

**Issue by SingleZombie** [Stable-X/StableNormal#9]
Thanks for your great work! Do you plan to share the training scripts and the dataset? Or any hints to build the dataset? You mentioned your dataset comes from GeoWizard but seems they don't offer the dataset, too.

**Comment by hugoycj** [comment]
We are cleaning training code. For access to the preprocessed dataset, you could contact me at [chongjieye@link.cuhk.edu.cn](mailto:chongjieye@link.cuhk.edu.cn)
